firebase:
  sign_up: "https://identitytoolkit.googleapis.com/v1/accounts:signUp?key=#{ENV['WEB_API_KEY']}"
  sign_in: "https://identitytoolkit.googleapis.com/v1/accounts:signInWithPassword?key=#{ENV['WEB_API_KEY']}"